export default [
  "Sea of Thieves",
  "R.B.I Baseball 18",
  "Attack on Titan 2",
  "Assault Gunners HD Edition",
  "Assassin's Creed Rogue: Remastered",
  "Kirby Star Allies",
  "Burnout Paradise Remastered",
  "Surviving Mars",
  "Gal Gunvolt Burst",
  "Q.U.B.E. 2",
  "Devil May Cry HD Collection",
  "Flinthook",
  "Warhammer: Vermintide 2",
  "Chuchel",
  "Damascus Gear: Operation Osaka",
  "Scribblenauts Showdown",
  "Frantics",
  "Final Fantasy XV",
  "Fear Effect Sedna",
  "DJMax Respect",
  "Bravo Team",
  "Pit People",
  "H1Z1",
  "Darkest Dungeon",
  "Payday 2",
  "Moss",
  "Heroine Anthem Zero",
  "Gravel",
  "Girls und Panzer: Dream Tank Match",
  "De Blob 2 Remastered",
  "Part Time UFO",
  "Yume Nikki: Dream Diary",
  "Sword Art Online: Fatal Bullet",
  "Past Cure",
  "Pac-Man Championship Edition 2 Plus",
  "Metal Gear Survive",
  "Armored Warfare",
  "Age of Empires: Definitive Edition",
  "Fe",
  "Bayonetta",
  "Bayonetta 2",
  "Secret of Mana",
  "A Certain Magical Virtual-On",
  "The Legend of Heroes: Trails of Cold Steel II",
  "The Legend of Heroes: Trails of Cold Steel",
  "The Longest 5 Minutes",
  "Radiant Historia: Perfect Chronology",
  "Owlboy",
  "Monster Energy Supercross: The Official Videogame",
  "Kingdom Come: Deliverance",
  "Dynasty Warriors 9",
  "Under Night In-Birth Exe: Late[st]",
  "The Seven Deadly Sins: Knights of Britannia",
  "Dragon Quest Builders",
  "Rust",
  "Octogeddon",
  "Civilization VI: Rise and Fall",
  "Shadow of the Colossus",
  "Marooners",
  "We Were Here Too",
  "Gundemoniums",
  "EA Sports UFC 3",
  "SteamWorld Dig",
  "Sky Force Reloaded",
  "Night in the Woods",
  "Dissidia Final Fantasy NT",
  "Monster Hunter: World",
  "Dragon Ball FighterZ",
  "Celeste",
  "The Inpatient",
  "Subnautica",
  "Lost Sphear",
  "Iconoclasts",
  "Kirby Battle Royale",
  "World to the West",
  "Gintama Rumble",
  "Darkest Dungeon",
  "Street Fighter V Arcade Edition",
  "Kerbal Space Program: Enhanced Edition",
  "InnerSpace",
  "The Escapists 2",
  "The Escapists",
  "Valkyria Chronicles 4",
  "A Way Out",
  "Ni no Kuni II: Revenant Kingdom",
  "Detective Pikachu",
  "Atelier Lydie & Suelle: The Alchemists and the Mysterious Paintings",
  "Far Cry 5",
  "Far Cry 4",
  "Far Cry 3",
  "MLB The Show 18",
  "Long Gone Days",
  "Shining Resonance Refrain",
  "Shining Force",
  "Shining in the Dark",
  "Super Robot Wars X",
  "Dark Rose Valkyrie",
  "Extinction",
  "God of War",
  "Nintendo Labo Variety Kit",
  "Nintendo Labo Robot Kit",
  "Adventure Time: Pirates of the Enchiridion",
  "Frostpunk",
  "South Park: The Fractured but Whole",
  "BattleTech",
  "Donkey Kong Country: Tropical Freeze",
  "Pillars of Eternity II: Deadfire",
  "Conan Exiles",
  "Hyrule Warriors: Definitive Edition",
  "State of Decay 2",
  "Dark Souls Remastered",
  "Detroit: Become Human",
  "Vampyr",
  "Street Fighter 30th Anniversary Collection",
  "Full Metal Panic! Fight: Who Dares Wins",
  "Sushi Striker: The Way of Sushido",
  "Jurassic World Evolution",
  "Mario Tennis Aces",
  "The Crew 2",
  "Captain Toad: Treasure Tracker",
  "Octopath Traveler",
  "WarioWare Gold",
  "Shadow of the Tomb Raider",
  "Call of Duty: Black Ops 4",
  "Red Dead Redemption 2",
  "Red Dead Redemption",
  "Anno 1800",
  "Call of Cthulhu",
  "Catherine: Full Body",
  "Concrete Genie",
  "Pony Island",
  "Amplitude",
  "Hardware: Rivals",
  "Volume",
  "Punch Club",
  "Lovely Planet",
  "Assassin's Creed Chronicles: India",
  "Gemini: Heroes Reborn",
  "Gone Home: Console Edition",
  "The Banner Saga",
  "That Dragon, Cancer",
  "Dragon's Dogma: Dark Arisen",
  "A Boy and His Blob",
  "Darkest Dungeon",
  "Oddworld: New 'n' Tasty!",
  "Resident Evil Zero HD Remaster",
  "The Deadly Tower of Monsters",
  "World of Tanks",
  "Homeworld: Deserts of Kharak",
  "Minecraft: Story Mode: Episode 1 — The Order of the Stone",
  "The Westport Independent",
  "Mario & Luigi: Paper Jam",
  "Lego Marvel's Avengers",
  "The Witness",
  "Rise of the Tomb Raider",
  "Bombshell",
  "This War of Mine: The Little Ones",
  "American Truck Simulator",
  "Digimon Story: Cyber Sleuth",
  "Megadimension Neptunia VII",
  "Tales of Symphonia HD",
  "Agatha Christie: The ABC Murders",
  "Assassin's Creed Chronicles: Russia",
  "XCOM 2",
  "Final Fantasy IX",
  "Lovers in a Dangerous Spacetime",
  "Naruto Shippuden: Ultimate Ninja Storm 4",
  "Grand Theft Auto: Liberty City Stories Mobile",
  "Pillars of Eternity: The White March Part 2",
  "Project X Zone 2",
  "The Escapists: The Walking Dead",
  "Rocket League",
  "Danganronpa: Trigger Happy Havoc",
  "Far Cry Primal",
  "Plants vs. Zombies: Garden Warfare 2",
  "The Flame in the Flood",
  "Gears of War: Ultimate Edition",
  "The Witch and the Hundred Knight: Revival Edition",
  "Heavy Rain",
  "BlazBlue: Chrono Phantasma Extend",
  "Black Desert Online",
  "The Legend of Zelda: Twilight Princess HD",
  "Tom Clancy's The Division",
  "Shadow Complex Remastered",
  "XCOM: Enemy Unknown",
  "Adventure Time: Magic Man's Head Games",
  "Keep Talking and Nobody Explodes",
  "Minecraft: Story Mode Episode 5 — Order Up!",
  "Ashes of the Singularity",
  "Sleeping Dogs: Definitive Edition",
  "1979 Revolution: Black Friday",
  "Sorcery! Part 3: The Seven Serpents",
  "Skullgirls 2nd Encore",
  "Everybody's Gone to the Rapture",
  "Dark Souls III",
  "Loud on Planet X",
  "The Banner Saga 2",
  "The Banner Saga",
  "Hyperdevotion Noire: Goddess Black Heart",
  "Stranger of Sword City",
  "Offworld Trading Company",
  "Uncharted 4: A Thief's End",
  "Shadow of the Beast",
  "Total War: Warhammer",
  "Dead Island: Definitive Edition",
  "Hearts of Iron IV",
  "Guilty Gear Xrd -Revelator-",
  "Sherlock Holmes: The Devil's Daughter",
  "Deadlight: Director’s Cut",
  "Mario & Sonic at the Rio 2016 Olympic Games",
  "Lost Sea",
  "Crypt of the Necrodancer Pocket Edition",
  "Crypt of the Necrodancer",
  "Romance of the Three Kingdoms XIII",
  "Assault Suit Leynos",
  "Mobile Suit Gundam: Extreme VS Force",
  "Kerbal Space Program",
  "Batman: Arkham Underworld",
  "Earth Defense Force 4.1: The Shadow of New Despair",
  "Kentucky Route Zero Act 4",
  "Fairy Fencer F: Advent Dark Force",
  "Stardew Valley",
  "Xblaze: Lost Memories",
  "The Girl and the Robot",
  "Master of Orion: Conquer the Stars",
  "Star Trek Online",
  "Pro Evolution Soccer 2017",
  "The Witness",
  "NBA 2K17",
  "NBA 2K14",
  "NBA 2K12",
  "NBA 2K9",
  "NBA 2K10",
  "FIFA 17",
  "FIFA 2007",
  "FIFA 08",
  "FIFA 15",
  "FIFA 12",
  "FIFA 98",
  "NFL Blitz",
  "Call of Cthulhu: The Wasted Land",
  "Double Fine Happy Action Theater",
  "Kingdoms of Amalur: Reckoning",
  "Shank 2",
  "Shank",
  "Jagged Alliance: Back in Action",
  "Tales of the Abyss",
  "Grand Slam Tennis 2",
  "Crusader Kings II",
  "Dear Esther",
  "Little Deviants",
  "Metal Gear Solid: Snake Eater 3D",
  "Dynasty Warriors Next",
  "Hot Shots Golf: World International",
  "Lumines: Electronic Symphony",
  "Wipeout 2048",
  "Shin Megami Tensei: Devil Survivor 2",
  "Vessel",
  "MLB 12: The Show",
  "Street Fighter X Tekken",
  "Mario Party 9",
  "Dungeon Defenders",
  "Total War: Shogun 2 – Fall of the Samurai",
  "Rayman Origins",
  "BioShock 2",
  "BioShock",
  "BioShock Infinite",
  "The House of the Dead 4",
  "Insanely Twisted Shadow Planet",
  "The Witcher 2: Assassins of Kings Enhanced Edition",
  "Port Royale 3: Pirates & Merchants",
  "Diablo III",
  "Diablo 2",
  "Diablo",
  "Mario Tennis Open",
  "Resident Evil: Operation Raccoon City",
  "Metal Gear Solid HD Collection",
  "Pokémon Conquest",
  "Civilization V: Gods & Kings",
  "Tom Clancy's Ghost Recon: Future Soldier",
  "Final Fantasy III",
  "The Amazing Spider-Man",
  "Tony Hawk's Pro Skater HD",
  "Growlanser Wayfarer of Time",
  "Persona 4 Arena",
  "Persona 4",
  "The Last Story",
  "Madden NFL 13",
  "Rock Band Blitz",
  "Anomaly: Warzone Earth",
  "Tekken Tag Tournament 2",
  "Torchlight II",
  "Torchlight",
  "Tokyo Jungle",
  "Marvel vs. Capcom Origins",
  "Dishonored",
  "RollerCoaster Tycoon 3D",
  "Carmageddon",
  "The Witcher 2: Assassins of Kings",
  "Medal of Honor: Warfighter",
  "Assassin's Creed III",
  "Ragnarok Tactics",
  "Paper Mario: Sticker Star",
  "Thomas Was Alone",
  "Epic Mickey: Power of Illusion",
  "Virtua Fighter 2",
  "Legacy of Kain: Soul Reaver",
  "Grand Theft Auto: San Andreas",
  "Final Fantasy IV",
  "Oddworld: Munch's Oddysee",
  "Divinity II: Ego Draconis",
  "Bayonetta",
  "Vandal Hearts: Flames of Judgment",
  "Mass Effect 2",
  "No More Heroes 2: Desperate Struggle",
  "S.T.A.L.K.E.R.: Call of Pripyat",
  "Deadly Premonition",
  "Risen",
  "Napoleon: Total War",
  "MLB 2K10",
  "Final Fantasy XIII",
  "God of War III",
  "Dead or Alive Paradise",
  "Mega Man 10",
  "Flotilla",
  "Monster Hunter Tri",
  "Alan Wake",
  "UFC 2010",
  "River City Soccer Hooligans",
  "Prince of Persia: The Forgotten Sands",
  "Ninety-Nine Nights II",
  "Singularity",
  "StarCraft II: Wings of Liberty",
  "Madden NFL 11",
  "Victoria 2",
  "Victoria",
  "Mafia II",
  "Mafia 3",
  "Phantasy Star II",
  "Phantasy Star IV",
  "Spider-Man: Shattered Dimensions",
  "Lost Horizon",
  "Front Mission Evolved",
  "Final Fantasy XIV",
  "Quantum Theory",
  "Castlevania: Lords of Shadow",
  "NBA Jam",
  "Lost Planet 2",
  "Sonic the Hedgehog 4: Episode 1",
  "Naruto Shippuden: Ultimate Ninja Storm 2",
  "Fallout: New Vegas",
  "Vanquish",
  "Fable III",
  "FIFA Manager 11",
  "God of War: Ghost of Sparta",
  "The Penguins of Madagascar",
  "Football Manager 2011",
  "Assassin's Creed: Brotherhood",
  "Pac-Man Party",
  "Tom Clancy's Ghost Recon",
  "Need for Speed: Hot Pursuit",
  "Gran Turismo 5",
  "Golden Sun: Dark Dawn",
  "Super Meat Boy",
  "World of Warcraft: Cataclysm",
  "Secret of Mana",
  "Saints Row 2",
  "Street Fighter IV",
  "Star Ocean: The Last Hope",
  "Warhammer 40,000: Dawn of War II",
  "Empire: Total War",
  "The Maw",
  "Resident Evil 5",
  "Valkyrie Profile: Covenant of the Plume",
  "Suikoden Tierkreis",
  "The Last Remnant",
  "Ninja Blade",
  "Dynasty Warriors: Gundam 2",
  "inFamous",
  "Gunstar Heroes",
  "Anno 1404",
  "Overlord: Dark Legend",
  "Overlord II",
  "Call of Juarez: Bound in Blood",
  "BlazBlue: Calamity Trigger",
  "Tales of Monkey Island",
  "Resident Evil 4",
  "Rez",
  "Mobile Suit Gundam: Zeonic Front",
  "Medal of Honor: Allied Assault",
  "MotoGP 2",
  "PaRappa the Rapper 2",
  "Grandia II",
  "Sonic Advance",
  "Super Mario Advance 2: Super Mario World",
  "Star Wars: Racer Revenge",
  "Zone of the Enders: The Fist of Mars",
  "Tony Hawk's Pro Skater 3",
  "Dungeon Siege",
  "The Elder Scrolls III: Morrowind",
  "Tactics Ogre: The Knight of Lodis",
  "Dragon Ball Z: The Legacy of Goku",
  "Looney Tunes: Space Race",
  "The House of the Dead III",
  "Digimon World 3",
  "Neverwinter Nights",
  "Shantae",
  "Warcraft III: Reign of Chaos",
  "Duke Nukem Advance",
  "Medieval: Total War",
  "Armored Core 3",
  "Armored Core",
  "Battlefield 1942",
  "Mega Man Zero",
  "Kingdom Hearts",
  "Dynasty Tactics",
  "Divine Divinity",
  "Super Mario Advance 3: Yoshi's Island",
  "Spyro 2: Season of Flame",
  "Hitman 2: Silent Assassin",
  "Virtua Tennis",
  "Mario Party 4",
  "Suikoden III",
  "NHL 2K3",
  "MechAssault",
  "Tom Clancy's Splinter Cell",
  "Ninja Assault",
  "Star Wars Jedi Knight II: Jedi Outcast",
  "Steel Battalion",
  "Gauntlet: Dark Legacy",
  "Final Fantasy Tactics",
  "Xenogears",
  "Yoshi's Story",
  "SaGa Frontier",
  "Panzer Dragoon Saga",
  "Star Ocean: The Second Story",
  "Commandos: Behind Enemy Lines",
  "Heart of Darkness",
  "Parasite Eve",
  "Caesar III",
  "Pokémon Blue",
  "Pokémon Red",
  "Pokémon Yellow",
  "Half-Life",
  "The Legend of Zelda: Ocarina of Time",
  "Star Wars: Rogue Squadron",
  "Baldur's Gate",
  "Falcon 4.0",
  "Civilization II",
  "Super Mario 64",
  "Star Ocean",
  "Tekken 2",
  "Madden NFL 97",
  "Master of Orion II",
  "Command & Conquer: Red Alert",
  "Dead or Alive",
  "Dragon Force",
  "Bust-a-Move",
  "Battle Arena Toshinden",
  "Chrono Trigger",
  "Super Bomberman 3",
  "Bomberman",
  "Twisted Metal",
  "Warcraft II: Tides of Darkness",
  "Tales of Phantasia",
  "World of Warcraft: The Burning Crusade",
  "Europa Universalis III",
  "Sonic the Hedgehog",
  "Jade Empire",
  "Theme Park",
  "S.T.A.L.K.E.R.: Shadow of Chernobyl",
  "Medal of Honor: Vanguard",
  "Command & Conquer 3: Tiberium Wars",
  "Guitar Hero II",
  "Guitar Hero",
  "Pokémon Pearl",
  "Pokémon Diamond",
  "Odin Sphere",
  "Mario Party 8",
  "Overlord",
  "Pokémon Battle Revolution",
  "Super Stardust HD",
  "Dynasty Warriors DS: Fighter's Battle",
  "Shin Megami Tensei: Persona 3",
  "The Settlers II",
  "Medieval II: Total War: Kingdoms",
  "Warhawk",
  "Medal of Honor: Airborne",
  "Skate",
  "Neverwinter Nights 2: Mask of the Betrayer",
  "Project Gotham Racing 4",
  "The Legend of Spyro: The Eternal Night",
  "Syphon Filter: Logan's Shadow",
  "Final Fantasy Tactics: The War of the Lions",
  "FIFA Soccer 08",
  "Half-Life 2",
  "Team Fortress 2",
  "Team Fortress",
  "Age of Empires III: The Asian Dynasties",
  "The Eye of Judgment",
  "Hellgate: London",
  "The Witcher",
  "Viva Piñata: Party Animals",
  "Fire Emblem: Radiant Dawn",
  "Call of Duty 4: Modern Warfare",
  "Silent Hill: Origins",
  "Super Mario Galaxy",
  "Enchanted",
  "Medal of Honor: Heroes 2",
  "WWE SmackDown vs. Raw 2008",
  "Kane & Lynch: Dead Men",
  "Orcs & Elves",
  "SimCity Societies",
  "Assassin's Creed",
  "Unreal Tournament 3",
  "Mass Effect",
  "Psychonauts",
  "Nights: Journey of Dreams",
  "SimCity 4",
  "Devil May Cry 2",
  "Dead or Alive Xtreme Beach Volleyball",
  "Capcom vs. SNK EO",
  "Tom Clancy's Splinter Cell",
  "Dark Cloud 2",
  "Dark Cloud",
  "Freelancer",
  "Pokémon Ruby and Sapphire",
  "Amplitude",
  "Batman: Dark Tomorrow",
  "Dragon Ball Z: Ultimate Battle 22",
  "Midnight Club II",
  "Burnout 2: Point of Impact",
  "Golden Sun: The Lost Age",
  "Ikaruga",
  "Castlevania: Aria of Sorrow",
  "Rise of Nations",
  "Midnight Club II",
  "Wario World",
  "Arc the Lad: Twilight of the Spirits",
  "Warcraft III: The Frozen Throne",
  "WWE Wrestlemania XIX",
  "Anarchy Online: The Shadowlands",
  "Homeworld 2",
  "Homeworld",
  "Freedom Fighters",
  "Viewtiful Joe",
  "Time Crisis 3",
  "Tony Hawk's Underground",
  "Fire Emblem",
  "Onimusha Tactics",
  "Monster Rancher 4",
  "Monster Rancher 3",
  "Counter-Strike",
  "Prince of Persia: The Sands of Time",
  "Victoria: An Empire Under the Sun",
  "Beyond Good & Evil",
  "1080° Avalanche",
  "Silent Hill 3",
  "Saints Row 2",
  "Mirror's Edge",
  "Moon",
  "Skate 2",
  "Flower",
  "Halo Wars",
  "Killzone 2",
  "Killzone",
  "Tomb Raider: Underworld",
  "Let's Golf",
  "Resident Evil 5",
  "Mega Man 2",
  "Worms",
  "Sacred 2: Fallen Angel",
  "Punch-Out",
  "inFamous",
  "Red Faction: Guerrilla",
  "Anno 1404",
  "Blood Bowl",
  "NCAA Football 10",
  "Battlefield 1943",
  "Shatter",
  "Fat Princess",
  "Trials HD",
  "Madden NFL 10",
  "Metroid Prime",
  "Tomb Raider II",
  "Fate/unlimited codes",
  "IL-2 Sturmovik: Birds of Prey",
  "Mario & Luigi: Bowser's Inside Story",
  "Streets of Rage",
  "Scribblenauts",
  "Marvel: Ultimate Alliance",
  "Marvel: Ultimate Alliance 2",
  "Professor Layton and the Diabolical Box",
  "Kingdom Hearts 358/2 Days",
  "Canabalt",
  "Fieldrunners",
  "UmJammer Lammy",
  "Half-Minute Hero",
  "Brütal Legend",
  "Machinarium",
  "Tropico 3",
  "Trine",
  "Oddworld: Abe's Exoddus",
  "Borderlands",
  "Forza Motorsport 3",
  "Tekken 6",
  "Bayonetta",
  "Ninja Blade",
  "Dragon Age: Origins",
  "Jak and Daxter: The Lost Frontier",
  "Call of Duty: Modern Warfare",
  "Assassin's Creed: Bloodlines",
  "Angry Birds",
  "Uncharted 2: Among Thieves",
  "Minecraft",
  "Batman: Arkham Asylum",
  "Forza Motorsport 3",
  "Forza Motorsport 2",
  "Retro City Rampage",
  "The Cave",
  "Wrath of the White Witch",
  "Skulls of the Shogun",
  "Fire Emblem Awakening",
  "Sly Cooper: Thieves in Time",
  "Crysis 3",
  "Crysis 2",
  "Crysis",
  "Metal Gear Rising: Revengeance",
  "Super Hexagon",
  "SimCity",
  "Hotline Miami",
  "Terraria",
  "Canabalt HD",
  "Wizorb",
  "Ninja Gaiden 3: Razor's Edge",
  "Age of Empires II: HD Edition",
  "Motocross Madness",
  "Gemini Rue",
  "Surgeon Simulator 2013",
  "Dragon's Dogma: Dark Arisen",
  "Carmageddon",
  "Dragon's Lair",
  "Ratchet & Clank: Full Frontal Assault",
  "Limbo",
  "Neverwinter",
  "TowerFall",
  "Rogue Legacy",
  "Crazy Taxi",
  "Dynasty Warriors 8",
  "Dropchord",
  "Dragon's Crown",
  "Tales of Xillia",
  "Mario & Luigi: Dream Team",
  "Gone Home",
  "Plants vs. Zombies 2: It's About Time",
  "Final Fantasy XIV: A Realm Reborn",
  "Valhalla Knights 3",
  "Battlefield 4",
  "Crimson Dragon",
  "Dead Rising 3",
  "Madden NFL 25",
  "Peggle 2",
  "Peggle",
  "The Stanley Parable",
  "Dr. Luigi",
  "Dota 2",
  "Rayman Legends"];
