const model = {
  game: {
    location: [
      'America',
      'Tokyo',
      'United States',
      'Soviet Russia',
      'Boston',
      'Britain',
      'Egypt',
      'Athens',
      'Moscow',
      'Washington D.C.',
      'Hell',
      'World War II',
      'Medieval Europe',
      'rural America',
      'City',
      "Shoshone National Forest",
      "Maximum Security Prison",
      "California",
    ],
    setting: [
      'bizarre',
      'post-apocalyptic',
      'underwater',
      'post-human',
      'rundown',
      'ruined',
      'desolate',
      'steampunk',
      'silkpunk',
      'fantastical',
      'dilapidated',
      'dystopic',
      'intergalactic',
      'eldritch',
      'ancient',
      'medieval',
      'cyperpunk',
      'fantasy',
      'alternate history',
      'gothic',
    ],
    genre: [
      'superhero',
      'horror',
      'racing',
      'puzzle',
      'metroidvania',
      'arcade',
      'side scroller',
      'action',
      'strategy',
      'RPG',
      'JRPG',
      'RPG-lite',
      'sports RPG',
      'first person shooter',
      'third person shooter',
      'visual novel',
      'platformer',
      'action platformer',
      'split-screen co-op',
      'simulation',
      'action-role playing',
      'city-sim',
      'flight simulator',
      'grand strategy',
      'real-time strategy',
      'farming',
      'walking simulator',
      'text adventure',
      'adventure',
      'action-adventure',
      'action sports',
      'twin-stick shooter',
      'clicker',
      'MMO',
      'MOBA',
      'fighting',
      'hockey',
      'football',
      'MMA',
      'character action',
      'rhythm',
      'open-world',
      'point-and-click adventure',
      'beat-\'em-up',
      'horizontal shoot-\'em-up',
      'vertical shooter',
      'hero shooter',
      'survival horror',
      'tower defense',
      'CCG',
      'action horror',
      'arcade racer',
      'basketball',
      'baseball',
      'puzzle',
      'puzzle platformer',
      'MMORPG',
      'survival sim',
      'survival',
      'roguelike',
      'dungeon crawler',
      'hack-and-slash'
    ],
    adjective: [
      'wholesome',
      'heartwarming',
      'surreal',
      'intense',
      'spooky',
      'grounded',
      'deep',
      'funny',
      'emotional',
      'macabre',
      'elegant',
    ],
    vocation: [
      'professional skater',
      'plumber',
      'astronaut',
      'soldier',
      'engineer',
      'tycoon',
      'superhero',
      'martial artist',
      'painter',
      'witcher',
      'magician',
      'black mage',
      'red mage',
      'rock star',
      'pirate',
      'rogue',
      'tennis player',
      'truck driver',
      'driver-for-hire',
      'cowboy',
    ],
    concept: [
      'friendship',
      'love',
      'motherhood',
      'fatherhood',
      'war',
      'hatred',
      'revenge',
      'anxiety',
      'tragedy',
      'death',
      'despair',
      'depression',
      'relationships',
      'science',
    ],
    personality: [
      'aging',
      'withered',
      'young',
      'brash',
      'stoic',
      'brazen',
      'happy-go-lucky',
      'mindless',
      'wizened',
      'foolish',
      'selfish'
    ]
  }
};

export default model;
