const model = {
  game: {
    location: [
      'America',
      'Tokyo',
      'United States',
      'Soviet Russia',
      'Boston',
      'Moscow',
      'Washington D.C.',
      'Hell',
      'World War II era Germany',
      'Medieval Europe',
      'rural America',
      'City',
      "Shoshone National Forest",
      "Maximum Security Prison",
      "California",
    ],
    setting: [
      'bizarre',
      'post-apocalyptic',
      'underwater',
      'post-human',
      'rundown',
      'ruined',
      'steampunk',
      'silkpunk',
      'fantastical',
      'dilapidated',
      'dystopic',
      'intergalactic',
      'eldritch',
      'medieval',
      'cyperpunk',
      'idealized',
      'fantasy',
      'alternate history',
      'gothic',
    ],
    genre: [
      'superhero',
      'horror',
      'racing',
      'puzzle',
      'metroidvania',
      'arcade',
      'side scroller',
      'action',
      'strategy',
      'RPG',
      'JRPG',
      'first person shooter',
      'third person shooter',
      'visual novel',
      'platformer',
      'action platformer',
      'split-screen co-op',
      'simulation',
      'action-role playing',
      'city-sim',
      'flight simulator',
      'grand strategy',
      'real-time strategy',
      'farming',
      'walking simulator',
      'text adventure',
      'adventure',
      'action-adventure',
      'action sports',
      'twin-stick shooter',
      'clicker',
      'MMO',
      'MOBA',
      'fighting',
      'hockey',
      'football',
      'MMA',
      'character action',
      'rhythm',
      'open-world',
      'point-and-click adventure',
      'beat-\'em-up',
      'horizontal shoot-\'em-up',
      'vertical shooter',
      'hero shooter',
      'survival horror',
      'tower defense',
      'CCG',
      'action horror',
      'arcade racer',
      'basketball',
      'baseball',
      'puzzle',
      'puzzle platformer',
      'MMORPG',
      'survival sim',
      'roguelike',
      'dungeon crawler',
      'hack-and-slash'
    ]
  }
};

export default model;
