const model = {
  game: {
    genre: [
      'superhero',
      'horror',
      'racing',
      'puzzle',
      'metroidvania',
      'arcade',
      'action',
      'strategy',
      'RPG',
      'first person shooter',
      'third person shooter',
      'visual novel',
      'platformer',
      'action platformer',
      'split-screen co-op',
      'simulation',
      'action-role playing',
      'city-sim',
      'flight simulator',
      'grand strategy',
      'real-time strategy',
      'farming',
      'walking simulator',
      'text adventure',
      'adventure',
      'action-adventure',
      'action sports',
      'twin-stick shooter',
      'clicker',
      'MMO',
      'MOBA',
      'fighting',
      'hockey',
      'football',
      'MMA',
      'character action',
      'rhythm',
      'open-world',
      'point-and-click adventure',
      'beat-\'em-up',
      'horizontal shoot-\'em-up',
      'vertical shooter',
      'hero shooter',
      'survival horror',
      'CCG',
      'action horror',
      'arcade racer',
    ]
  }
};

export default model;
