export default {
  "art-1": "It's rare for a game released in ::game.S.releaseDate:: to still look great, and yet ::game.S.title:: looks half its age.",
  "art-2": "It's ::art.platitude:: visuals and sound design quickly garnered the game a massive fandom.",
  "art-3": "When it hit the scene, ::game.S.title:: was one of the best-looking games out there.",
  "art-4": "::game.S.title::, at the time, was one of the best-looking games available.",
  "art-5": "::game.S.title:: featured a ::art.viewPoint:: view and visual depth that marked a big step forward for visuals — and gave players the impression they were in a different world.",
  "art-6": "Its ::art.platitude:: visuals completely moved the bar forward.",
  "art-7": "Unparalleled in detail at the time, ::game.S.title|possessive:: caught the eyes of critics and players, raising expectations for how games after it should look.",
  "art-8": "It was a super pretty game.",
  "art-9": "::game.S.title:: was one of the most ::art.platitude:: games when it released in ::game.S.releaseDate::.",
  "art-10": "::game.S.title:: was more ::art.platitude:: than almost any game released before or after.",
  "art-11": "Though its cartoony visuals were divisive at the time of release, ::game.S.title|possessive:: aesthetic made for an expressive game that has gained fans over time.",
  "art-12": "It was the most ::art.platitude::-looking game of its time.",
  "art-13": "It was considered a pinnacle of video game visuals in ::game.S.releaseDate::.",
  "art-14": "::game.S.title:: derives its strength from its high core production values.",
  "art-15": "Its ::art.platitude:: graphics form a cohesive, wonderous whole, and its sound effects where at the apex of ::game.S.releaseDate::.",
  "art-16": "It’s rare to encounter a game that so effectively transports you someplace so beautiful.",
  "art-17": "::game.S.title:: is all about movement and style, and it has both in spades.",
  "art-18": "Still one of the coolest games ever, ::game.S.title:: put style first, rewarding players for being flashy and violent.",
  "art-19": "::game.S.title:: revolutionized the way ::game.S.genre:: games could look and feel.",
  "art-20": "::game.S.title:: has a rich and ::art.platitude:: quality. It is the sort of game that demands a photo mode.",
  "art-21": "This is a game that grabs you and holds you, and it’s simple to get lost in the often sublime mixture of sights and sounds.",
  "art-22": "::game.S.title:: inhabits a sumptuous world of color and mystery that demands to be explored.",
}
