export default {
  "artStyle-0": "Nearly hypnotic, the game's gorgeous art-style make for a game as much a joy to look at as it is to play.",
  "artStyle-1": "It's rare for a game released in ::game.S.releaseDate:: to still look great, and yet ::game.S.title:: looks half its age.",
  "artStyle-2": "::game.S.title:: makes use of its minimalistic art direction to tell a story resonating with its players emotionally, making it one of the most renowned games of all time.",
  "artStyle-3": "Pairing the game's groundbreaking visuals with an incredibly smooth framerate, it turned out to be one of ::game.S.releaseDate|possessive:: most realistic games.",
  "artStyle-4": "Its tranquil visuals and sound design quickly garnered the game a massive fandom.",
  "artStyle-5": "When it hit the scene, ::game.S.title:: was one of the best-looking games out there.",
  "artStyle-6": "::game.S.title::, at the time, was one of the best looking games available.",
  "artStyle-7": "Its high frame rate, multiple camera angles and 3D NPCs made players feel closer to the action than ever before.",
  "artStyle-8": "A hyper-stylized take on the then-huge ::game.S.genre:: genre, ::game.S.title|possessive:: cel-shaded world, hip hop-influenced soundtrack and altogether zaniness made it stand out in a genre oversaturated with licensed tie-ins.",
  "artStyle-9": "::game.S.title:: used hand-drawn backgrounds and rotoscoped animations to make characters look lifelike.",
  "artStyle-10": "::game.S.title:: was a pioneer of cinematic games, with many critics praising its visuals, sound, and animation as innovative and top notch.",
  "artStyle-11": "::game.S.title:: featured a first-person view and visual depth that marked a big step forward for game visuals — and gave players the impression they were in a different world.",
  "artStyle-12": "Its visuals completely moved the bar forward.",
  "artStyle-13": "Unparalleled in detail at the time, ::game.S.title|possessive:: caught the eyes of critics and players, raising expectations for how games after it should look.",
  "artStyle-14": "Its beautiful, hand-drawn art style made it one of the best-looking games of its generation.",
  "artStyle-15": "It was a super pretty game.",
  "artStyle-16": "::game.S.title|possessive:: abstract, art house-like subversion of the ::game.S.genre:: is something you need to see to fully appreciate.",
  "artStyle-17": "Making use of Gouraud shading, ::game.S.title:: was more realistic looking than most games when it released.",
  "artStyle-18": "::game.S.title:: was one of the most technically impressive games when it released in ::game.S.releaseDate::.",
  "artStyle-19": "::game.S.title:: was more stylish than almost any game released before or after.",
  "artStyle-20": "Utilizing fixed cameras to give the game a cinematic look, ::game.S.title:: created a sense of tension unseen before as players walked through its numerous winding halls and traps.",
  "artStyle-21": "It features some of the smoothest animation ever seen in a ::game.S.title::.",
  "artStyle-22": "Though its cartoony visuals were divisive at the time of release, ::game.S.title|possessive:: aesthetic made for a more expressive game that has gained fans over time.",
  "artStyle-23": "It featured some of the best graphics of its time.",
  "artStyle-24": "It was considered a pinnacle of video game visuals in ::game.S.releaseDate::.",
  "artStyle-25": "Its art deco metropolis-gone-wrong style instantly engrossed players in the action, enticing them to search every corner to learn what went wrong.",
};
