export default {
  "critique-0": "::game.S.title:: tells a ::game.adjective:: story about ::game.concept:: and how to find common ground.",
  "critique-1": "::game.S.title|possessive:: story about ::game.concept:: and how to find common ground is told in ::game.adjective|articlize:: fashion.",
  "critique-2": "Equal parts John Huston and John Woo, it tells a story of addiction and ::game.concept::, all tied together into a game.",
  "critique-3": "Greater than the sum of its parts, the story ::game.S.title:: tells about ::game.setting:: capitalism makes it an important example of games as political satire.",
  "critique-4": "On the surface a game about ::game.setting:: politics and war, ::game.S.title:: is memorable for the ::game.adjective::, emotional relationship with ::game.concept:: which it asked the player to engage.",
  "critique-5": "::game.S.title:: pointed an angry finger right at the American dream.",
  "critique-6": "::game.S.title:: stood out as a game unafraid to examine sexuality in smart, nuanced ways — something hard to say about most games.",
  "critique-7": "::game.S.title|possessive:: mature take on infidelity, lust, love and abuse showed the depth that game stories could achieve.",
  "critique-8": "::game.S.title:: is a bleak story about ::game.concept:: gone wrong.",
  "critique-9": "The game's deep and trope-breaking story found success around the world.",
  "critique-10": "::game.S.title:: is about staying alive — even when it seems impossible.",
  "critique-11": "It tells a brutal, yet intimate ::game.setting:: story with some of the finest examples of character development in games.",
  "critique-12": "::game.S.title|possessive:: tale of ::game.concept::, lies, and the human condition set a new bar for storytelling in games — one that'll be hard to top.",
  "critique-13": "A cult classic, ::game.S.title|possessive:: rich story gets points for being smarter than its peers, casting players as ::game.personality|articlize:: protagonist with surprising depth.",
  "critique-14": "Lauded for its ::game.adjective:: story, ::game.S.title:: was about learning to work together, all the while growing closer.",
  "critique-15": "The masterfulness in which ::game.S.title:: told its story of ::game.setting:: travel, and the nuances and complexities in which the story is dissected by player choice, is one of the finer examples storytelling in video games.",
  "critique-16": "::game.S.title:: changed everything we knew about game writing. Focusing on the impact of every decision, it presented numerous heart-stopping experiences.",
  "critique-17": "It taught its players about American history while being immensely fun and engaging to interact with over the course of the game's long journey.",
  "critique-18": "The push and pull of the job and the personal life of your character made ::game.S.title:: an emotional experience, one emphasizing empathy over economic growth.",
  "critique-19": "Few games match the pacing of ::game.S.title::.",
  "critique-20": "Seemingly down to the second, ::game.S.title:: knew exactly when to put players through amazing set pieces, when to introduce puzzles and when to pull back for quieter, more intimate moments.",
  "critique-21": "::game.S.title:: was an amazing breakthrough in storytelling and a surprising reinvention of one of the oldest genres.",
  "critique-22": "::game.S.title:: ushered in a new era of intense plot, narration and dialog everywhere, but particularly in the ::game.S.genre:: genre.",
  "critique-23": "The ::game.adjective:: ::game.setting:: fantasy that was ::game.S.title:: left an impression on gamers that has rarely been matched.",
  "critique-24": "Telling a complex story about the nature of man, ::game.S.title:: offered one of the most unforgettable experiences in games.",
  "critique-25": "The game puts the lives of others in your hands — possibly at the cost of your family's safety. Upon its release, ::game.S.title:: was lauded for its intense moral dilemmas.",
  "critique-26": "::game.S.title:: was masterclass in how to write a plot twist and how to smash player expectations.",
  "critique-27": "::game.S.title:: let players become who they wanted.",
  "critique-28": "Games often lack nuanced understanding of human emotions and mental illnesses. ::game.S.title:: however, does not.",
  "critique-29": "Flawed. Full of heart. Unafraid. ::game.S.title:: took the ultra-gruff protagonist archetype and tore it to shreds.",
  "critique-30": "The story is like nothing else. Imagine your friend got really, really high while thinking about food and you transcribed their thoughts and handed them to a talented studio with the express orders of turning it all into a game with remarkably good production values.",
  "critique-31": "Make no mistake about it, ::game.S.title:: is a weird game. It’s wrapped around a concept featuring sentient hat and enemy possession, but actually playing the game feels very familiar.",
  "critique-32": "Its high design masks a surprisingly tense ::game.S.genre:: game that demands lateral thinking, bold reinvention, and ruthless economics.",
  "critique-33": "The game’s real innovation is its seances, frequently conducted by decoding patches of ominous white noise. Janky, gloomy, and suffused with a dark beauty, ::game.S.title:: is a true original.",
  "critique-34": "A thrilling ending that dares the player to put their money where their mouth is ensures ::game.S.title:: holds strong and stable even as it constantly darts forward to its next big thought.",
}
