export default {
  "difficulty-0": "::game.S.title:: helped popularize difficulty as a selling point.",
  "difficulty-1": "A game easy to pick up and instantly find satisfaction with, ::game.S.title:: constantly tempts you into playing it just a little longer with dangerously addictive gameplay.",
  "difficulty-2": "::game.S.title:: may very well be the magnum opus of ultra-difficult ::game.S.genre:: games.",
  "difficulty-3": "Requiring skill and fast responses, ::game.S.title|possessive:: fun-but-precise gameplay made it easy to pick up and play but a task to master.",
  "difficulty-4": "::game.S.title:: tapped into the part of the brain craving \"just one more go,\" leading to numerous lost days in its world.",
  "difficulty-5": "::game.S.title:: tried to marry two audiences: fans of weird humor and fans of difficult ::game.S.genre:: games.",
  "difficulty-6": "::game.S.title:: did away with ::game.S.genre:: conventions in favor of more approachable alternatives, making it a good first step into the genre.",
  "difficulty-7": "::game.S.title:: emphasized real(ish) combat focused on skill — especially when death is usually one hit away.",
  "difficulty-8": "One of the most complex games ever made, ::game.S.title:: is often described as a part-time job.",
  "difficulty-9": "::game.S.title:: was developed around being easy to understand and fun to play.",
  "difficulty-10": "It expertly rode the line between simulation and arcade experience, making it possible for players of all skill levels to jump in, play, and find something to love.",
  "difficulty-11": "::game.S.title:: helped establish games as challenges to overcome through skill and reflex.",
  "difficulty-12": "The notoriously hard final boss offered a true test of skill, making this a game players constantly came back to, thinking, \"I've got it this time.\"",
}
