export default {
  "features-0": "Featuring a then-novel concept, ::game.S.title:: let players choose the character they wanted to be and how they wanted to play.",
  "features-1": "Its innovative use of varied gameplay is an early example of a game pushing its gameplay beyond one schtick.",
  "features-2": "::game.S.title:: is a rare example of ::game.S.genre|articlize:: game incentivizing exploration.",
  "features-3": "Impossibly big, ::game.S.title:: gave players a world to lose themselves in.",
  "features-4": "Pitting two players against each other with only a sword — success in ::game.S.title:: relies equally on skill and luck.",
  "features-5": "::game.S.title:: combined visual novel elements to flesh out its lore and backstory, a move many saw as groundbreaking for the genre.",
  "features-6": "Tasking up to four players with breaking out of a castle, players were invited to utilize the interactive environment and items in the world to progress — something notable and revolutionary in ::game.S.releaseDate::.",
  "features-7": "Building upon great dungeon design and overall presentation, ::game.S.title:: also introduced new gameplay mechanics.",
  "features-8": "::game.S.title:: radically redefined how players could interact with environments and how cinema and games could blend together.",
  "features-9": "Full of unique, inventive \"microgames,\" ::game.S.title:: also made use of a built-in gyro sensor.",
  "features-10": "Though many tried to steal its successful formula after its release, it took awhile for anyone to match ::game.S.title|possessive:: addictive, trick-based gameplay loop.",
  "features-11": "No other game matches the attitude of ::game.S.title::.",
  "features-12": "::game.S.title:: changed multiplayer games forever.",
  "features-13": "::game.S.title:: is a game about planning, each level a maze of opportunities to explore.",
  "features-14": "Whether your plan is an all-out assault or a silent game of cat and mouse, ::game.S.title|possessive:: world constantly adapted to your choices in positive and negative ways.",
  "features-15": "Never telling players how to pull off an objective, ::game.S.title:: also never let them forget the repercussions their actions had on the game's world.",
  "features-16": "::game.S.title:: pit four players against each other, all fighting to destroy the others' castles while defending their own.",
  "features-17": "The sheer size of ::game.S.title:: is still unparalleled by most other games.",
  "features-18": "The game featured a near-uncountable number of secrets, minigames, and side missions.",
  "features-19": "The game introduced numerous mechanics players hadn't seen before.",
  "features-20": "Its emphasis on exploration has been highly influential in games being worlds to explore, not just obstacles to overcome.",
  "features-21": "Introducing killstreaks, a level-up system, and many other new features, ::game.S.title:: changed the dynamics of multiplayer games forever.",
  "features-22": "::game.S.title|possessive:: mechanics felt like a fresh start.",
  "features-23": "With countless approaches to the objectives, the game was built for the player to come up with all sorts of dynamic solutions.",
  "features-24": "It allowed players to see the world change based on how they approached different challenges.",
  "features-25": "It allowed three players to play together cooperatively, a rare feat for a game released in ::game.S.releaseDate::.",
}
