export default {
  "features-0": "Featuring a then-novel concept, ::game.S.title:: let players choose the character they wanted to be and how they wanted to play.",
  "features-1": "Its innovative use of varied gameplay is an early example of a game pushing its gameplay beyond one schtick.",
  "features-2": "::game.S.title:: is a rare example of ::game.S.genre|articlize:: game incentivizing exploration.",
  "features-3": "Impossibly big, ::game.S.title:: gave players a world to lose themselves in.",
  "features-4": "Pitting two players against each other with only a sword — success in ::game.S.title:: relies equally on skill and luck.",
  "features-5": "::game.S.title:: combined visual novel elements to flesh out its lore and backstory, a move many saw as groundbreaking for the genre.",
  "features-6": "Tasking up to four players with breaking out of a castle, players were invited to utilize the interactive environment and items in the world to progress — something notable and revolutionary in ::game.S.releaseDate::.",
  "features-7": "Building upon great dungeon design and overall presentation, ::game.S.title:: also introduced new gameplay mechanics such as the ability to merge into walls",
  "features-8": "::game.S.title:: radically redefined how players could interact with environments and how cinema and games could blend together.",
  "features-9": "Full of unique, inventive \"microgames,\" ::game.S.title:: also made use of a built-in gyro sensor.",
  "features-10": "Though many tried to steal its successful formula after its release, it took awhile for anyone to match ::game.S.title|possessive:: addictive, trick-based gameplay loop.",
  "features-11": "No other game matches the attitude of ::game.S.title::.",
  "features-12": "::game.S.title:: changed multiplayer games forever.",
  "features-13": "::game.S.title:: is a game about planning, each level a maze of opportunities to explore.",
  "features-14": "Whether your plan is an all-out assault or a silent game of cat and mouse, ::game.S.title|possessive:: world constantly adapted to your choices in positive and negative ways.",
  "features-15": "Never telling players how to pull off an objective, ::game.S.title:: also never let them forget the repercussions their actions had on the game's world.",
}
