export default {
  "features-0": "Featuring a then-novel concept, ::game.S.title:: let players choose the character they wanted to be and how they wanted to play.",
  "features-1": "Its innovative use of varied gameplay is an early example of a game pushing its gameplay beyond one schtick.",
  "features-2": "::game.S.title:: is a rare example of ::game.S.genre|articlize:: game incentivizing exploration.",
  "features-3": "Impossibly big, ::game.S.title:: gave players a world to lose themselves in.",
  "features-4": "No other game has matched the fluid grace of its brilliant mechanics.",
  "features-5": "::game.S.title:: combined visual novel elements to flesh out its lore and backstory, a move many saw as groundbreaking for the genre.",
  "features-6": "Tasking up to four players with breaking out of a castle, players were invited to utilize the interactive environment and items in the world to progress — something notable and revolutionary in ::game.S.releaseDate::.",
  "features-7": "Building upon great dungeon design and overall presentation, ::game.S.title:: also introduced new gameplay mechanics.",
  "features-8": "::game.S.title:: radically redefined how players could interact with environments and how cinema and games could blend together.",
  "features-9": "Full of unique, inventive \"microgames,\" ::game.S.title:: also made use of a built-in gyro sensor.",
  "features-10": "Though many tried to steal its successful formula after its release, it took awhile for anyone to match ::game.S.title|possessive:: addictive, trick-based gameplay loop.",
  "features-11": "No other game matches the attitude of ::game.S.title::.",
  "features-12": "::game.S.title:: changed multiplayer games forever.",
  "features-13": "::game.S.title:: is a game about planning, each level a maze of opportunities to explore.",
  "features-14": "Whether your plan is an all-out assault or a silent game of cat and mouse, ::game.S.title|possessive:: world constantly adapted to your choices in positive and negative ways.",
  "features-15": "Never telling players how to pull off an objective, ::game.S.title:: also never let them forget the repercussions their actions had on the game's world.",
  "features-16": "::game.S.title:: pit four players against each other, all fighting to destroy the others' castles while defending their own.",
  "features-17": "The sheer size of ::game.S.title:: is still unparalleled by most other games.",
  "features-18": "The game featured a near-uncountable number of secrets, minigames, and side missions.",
  "features-19": "The game introduced numerous mechanics players hadn't seen before.",
  "features-20": "Its emphasis on exploration has been highly influential in games being worlds to explore, not just obstacles to overcome.",
  "features-21": "Introducing killstreaks, a level-up system, and many other new features, ::game.S.title:: changed the dynamics of multiplayer games forever.",
  "features-22": "::game.S.title|possessive:: mechanics felt like a fresh start.",
  "features-23": "With countless approaches to the objectives, the game was built for the player to come up with all sorts of dynamic solutions.",
  "features-24": "It allowed players to see the world change based on how they approached different challenges.",
  "features-25": "It allowed three players to play together cooperatively, a rare feat for a game released in ::game.S.releaseDate::.",
  "features-26": "Built to facilitate thousands of players at once, the game became famous for its massive, months-long events where hundreds, sometimes thousands of players would band together to take on entire cities.",
  "features-27": "::game.S.title:: set new standards with its sheer world size, quest depth and character options.",
  "features-28": "Developed by a supergroup of creative minds, ::game.S.title:: innovated with features like multiple endings and side quests that tied into the main plot.",
  "features-29": "The game reached beyond the confines of one city, its fictional world featured numerous terrains and multiple cities.",
  "features-30": "Unlike a lot of games at the time of its release, ::game.S.title:: told its story completely in-game, free of cutscenes.",
  "features-31": "The great world design allowed players to slip into ::game.S.title|possessive:: world, personally engaging with the story more than in other games.",
  "features-32": "::game.S.title:: marked the pinnacle of agency and consequences.",
  "features-33": "The bonds you form with your many crewmates throughout the game will have you replaying the game to make sure you savor every, last, one.",
  "features-34": "The ever-changing gameplay — dictated on the fly by the game's A.I. \"Director\" — kept each playthrough interesting.",
  "features-35": "Incredibly ambitious, the sheer amount of content and meticulous world design made for a game still considered one of the best in the genre.",
  "features-36": "::game.S.title|possessive:: multiplayer alone is enough to secure a spot on this list.",
  "features-37": "The game's expansive roster and unique special moves make for something special.",
  "features-38": "The degree to which the game's buildings and structures could be torn apart changed how scenarios could be approached and found critical praise.",
  "features-39": "::game.S.title|possessive:: approach to destruction forced players to be more active and experimental.",
  "features-40": "The game set a new standard for the way games presented real-life activities.",
  "features-41": "::game.S.title:: felt overwhelming due to waves of enemies that exploded into bright, colorful particles.",
  "features-42": "::game.S.title|possessive:: perspective made it engulfing, incentivizing further exploration and leading players around every corner.",
  "features-43": "::game.S.title|possessive:: character roster stands out, even today.",
  "features-44": "::game.S.title:: gave players a host of customization options and ways to interact with the world.",
  "features-45": "::game.S.title:: featured a cast of unique, funny characters, a different approach at a moment in time when many games featured voiceless killing apparatuses.",
  "features-46": "::game.S.title:: gave players three continents to explore and 14 classes/12 races to choose from when creating a character.",
  "features-47": "::game.S.title:: let you experiment in your approach, changing your play style to make each attempt a little bit different than the last.",
  "features-48": "Wholly unique, ::game.S.title:: format was one that could only exist as a game, and it was better for it.",
  "features-49": "::game.S.title:: still stands out for how it brought four players together for something more than competition.",
  "features-50": "Focused on rewards, ::game.S.title|possessive:: feedback loop of fight-then-receive-loot influenced countless other games to implement similar structures.",
  "features-51": "Its wide cast of wild characters, exciting open world, and amazing soundtrack made ::game.S.title:: one of the best games of all time.",
  "features-52": "Its map editor allowed players to create and play their own multiplayer maps.",
  "features-53": "Its one of the industry's best examples of local multiplayer.",
  "features-54": "::game.S.title:: struck a beautiful balance between deep mechanics and fast, fluid execution.",
  "features-55": "Abandoning the obtuse design and seemingly random punishments many were accustomed to from similar games, ::game.S.title:: appealed to enough players to spawn several sequels and spinoffs.",
  "features-56": "::game.S.title:: sports the most creative and varied level design of any ::game.S.genre:: game, bar none.",
  "features-57": "The variety of ::game.S.title|possessive:: monsters, items and weapons provide the player with a million ways to attack the same problem.",
  "features-58": "Featuring the most extensive character creators up to that point, players were free to be creative with their personas, giving them the chance to roleplay like never before.",
  "features-59": "::game.S.title:: is one of those games so simple in its design, you rarely realize how brilliant it is.",
  "features-60": "A Japanese-style ninja fantasy featuring a grappling hook, the game offers a verticality in its level-design not often seen in similar games.",
  "features-61": "It features a humongous open world powered by an amazing engine.",
  "features-62": "::game.S.title:: lets players play as a man or woman, romance who they want regardless of gender, and participate in conversation via dialogue trees.",
  "features-63": "The social features, persistent weather and seasonal effects help give the ::game.S.location:: setting depth and a sense of shared experience.",
  "features-64": "All of ::game.S.title|possessive:: interlocking systems make for an arresting time sink that merges logic, forethought, psychology and experimentation.",
  "features-65": "::game.S.title:: set out to make us laugh — no easy task in a video game — and delivered in spades. Only the dourest soul could fail to crack a smile at its silly antics.",
  "features-66": "::game.S.title:: is smart about how it teaches you game mechanics, providing the freedom to play however you want right from the outset.",
  "features-67": "::game.S.title:: is all about the power of friendship. In this adventure, players have a single button used exclusively for befriending enemies.",
  "features-68": "Rapid mechanical switch-up isn’t the exception in ::game.S.title::, it’s the rule. The game marries two key elements: satisfying game mechanics and level design that brings out the best in them.",
  "features-69": "::game.S.title:: is all about the providing moment-to-moment gameplay that is its own reward.",
  "features-70": "::game.S.title:: sets an immensely high bar for storytelling, exuding careful and deliberate artistry in every aspect to create a world worth exploring.",
  "features-71": "Its greatest strength might be its minimal text.",

}
