export default {
  "general-0": "::game.S.title:: birthed some of the greatest games of all time.",
  "general-1": "For every game sparking conversations about games as high art, another's there to remind us they can be weird.",
  "general-3": "The game maintains a cult following and spawned a sequel iterating on the bizarre approach to level design that made ::game.S.title:: a memorable journey.",
  "general-4": "It's great dumb fun.",
  "general-5": "::game.S.title:: was bombastic, scary and stunning.",
  "general-6": "Better than its film counterpart, ::game.S.title:: is a notable exception to the consensus that film-based games are needless cash tie-ins.",
  "general-7": "::game.S.title:: was able to grab awards from the Academy of Interactive Arts & Sciences, as well as nominations for its design from the Game Developers Choice Awards.",
  "general-8": "In Stockholm, the game was recently used to design and test urban planning.",
  "general-9": "::game.S.title:: abandoned the mission-to-mission structure of earlier games, allowing players to explore and interact with its Victorian-styled world, creating a more engaging, accessible, immersive sim.",
  "general-10": "Changing the world with every playthrough, ::game.S.title|possessive:: only objective is to explore — but at your leisure.",
  "general-11": "There's no princess to save or enemy to kill. It's simply a meditative experience through imaginary worlds, an experience only possible in games.",
  "general-12": "::game.S.title:: is the Occam's Razor of video games.",
  "general-13": "::game.S.title:: tempted players to keep exploring, all the while reminding them death was only one step away.",
  "general-14": "::game.S.title:: drove home the idea that games didn't necessarily need clear-cut objectives.",
  "general-15": "::game.S.title:: exhibited remarkable attention to detail.",
  "general-16": "It took no time for ::game.S.title:: to surpass all expectations.",
  "general-17": "It has become a popular speedrunning game.",
  "general-18": "The game gained a cult-following that led to it being featured in the Museum of Modern Art.",
  "general-19": "::game.S.title:: is often remembered for its unique Easter egg.",
  "general-20": "::game.S.title:: dared to be different.",
  "general-21": "::game.S.title:: got credit for being both fun and a learning experience about economics.",
  "general-22": "The game was supposedly developed to facilitate up to 10,000 players, though it never reached that number.",
  "general-23": "::game.S.title:: has remained one of Steam's most popular games, hitting one million concurrents at its peak.",
  "general-24": "The game has also been one of the biggest success stories in the esports world, with some prize pools topping $20 million.",
  "general-25": "With more than 100 million people playing ::game.S.title:: every month, it's hard to think of bigger game.",
  "general-26": "::game.S.title:: is one of the most lucrative esports titles in the world, with top prize pools totalling more than $6 million.",
  "general-27": "Requiring only one hand to operate and needing a second player to go against, ::game.S.title|possessive:: popularity rose in part to its frequent placement in bars.",
  "general-28": "::game.S.title:: charming sense of humor, surprisingly awesome soundtrack and addictive gameplay made gave it a true sense of character.",
  "general-29": "::game.S.title|possessive:: revolutionary active playstyle has helped the series stand the test of time.",
  "general-30": "::game.S.title:: innovated the amount of depth a game can have.",
  "general-31": "Very few games have built identity, history, and genre like ::game.S.title::.",
  "general-32": "::game.S.title:: is a masterclass in how to modernize a classic game.",
  "general-33": "::game.S.title:: became one of the most addictive games ever released.",
  "general-34": "::game.S.title:: added a modern sheen to a classic genre.",
  "general-35": "Though not the first game to feature crossover characters, its use of big names stood out from the pack.",
  "general-36": "Online only, ::game.S.title:: was awash with thousands of players trying to prove their skills.",
  "general-37": "::game.S.title:: felt like playing with action figures.",
  "general-38": "::game.S.title:: went on to shape the competitive gaming scene.",
  "general-39": "One of the most widespread games of all time, ::game.S.title:: gamified learning.",
  "general-40": "::game.S.title:: evolved online gaming in its own small way.",
  "general-41": "::game.S.title:: shattered any preconceived notions of what to expect from a game, proving games can be whatever you want them to be.",
  "general-42": "Because of its realistic approach, ::game.S.title:: and its sequels have become staples of the esports industry.",
  "general-43": "It was like nothing players had seen before.",
  "general-44": "It was fast. It was cool. It had attitude.",
  "general-45": "::game.S.title:: focused primarily on action, making it more exciting than many of its competitors.",
  "general-46": "When it released, ::game.S.title:: felt like a breath of fresh air.",
  "general-47": "Since release, the game's consistently been a star attraction for tournaments paying out well over $100,000.",
  "general-48": "This was one of the best licensed games of its time due to its ability to make you feel like you were in the action.",
  "general-49": "Praised for its revolutionary graphics and funny story, the game maintains a cult status to this day.",
  "general-50": "::game.S.title:: was one of the most popular games released in ::game.S.releaseDate::.",
  "general-51": "::game.S.title:: was a great example of a game challenging the conventional models of the industry.",
  "general-52": "Its title song was the first game track to win a Grammy, so that's cool.",
  "general-53": "::game.S.title:: was more about the journey than the destination.",
  "general-54": "People still talk about ::game.S.title|possessive:: depth and mature approach to romance options, allowing players to choose their sexual orientation.",
  "general-55": "The game maintains a cult following and spawned a sequel iterating on the bizarre approach to level design that made ::game.S.title:: a memorable journey.",
  "general-56": "It's easy to see ::game.S.title:: as a fad, something for retailers to slap on children's clothes and backpacks.",
  "general-57": "Since its release, the game has been plastered on millions of shirts and even received its own feature length film.",
  "general-58": "It also birthed what's thought of as one of the best DLC episodes of all time.",
  "general-59": "With 22.8 million players making the game $43.4 million within its first quarter of release, ::game.S.title:: reached — and continues to reach — more players than most critically acclaimed games.",
  "general-60": "The success of ::game.S.title:: was so tremendous that it was adapted into other media like comics, television and film.",
  "general-61": "Just ignore the online issues.",
  "general-62": "In 2018, Emmett/Furla/Oasis Films secured the rights to make a ::game.S.title:: movie.",
  "general-63": "It’s an enveloping, relaxing experience, allowing players to sit back and let the game wash over them.",
  "general-64": "It’s weird, gross and incredibly fun.",
  "general-65": "::game.S.title:: has, in many ways, as close to a perfect story as we’ve seen from a massive AAA title.",
  "general-66": "::game.S.title:: is a game that allows us to process what’s happening in this world within the safe (and beautifully animated) confines of a virtual one.",
  "general-67": "It’s rare for a game to grab the player this strongly solely with its visuals.",
  "general-68": "::game.S.title:: feels like going to your favorite restaurant and ordering your favorite dish, and finding out that today it will be prepared and garnished with ritzy, fresh ingredients.",
  "general-69": "::game.S.title:: is a useful reminder that the ::game.S.genre:: genre can entertain us in the here and now, while straining toward a more thrilling tomorrow.",
  "general-70": "It is unadulterated joy, providing a frantic experience that never ceases to delight.",
  "general-71": "There’s a strange, almost hypnotic flow to ::game.S.title::.",
  "general-72": "The game feels like a complete joy to play, and all of its moving parts snap together tightly, rewarding a clear head and steady hands.",
  "general-73": "::game.S.title:: has a raucous, concussive energy stemming from the seemingly impossible nature of its visually stunning action.",
  "general-74": "The breathless pace of new ideas and the speed of the action is unrelenting in a breakneck way that shouldn’t work, yet paradoxically feels relaxing.",
  "general-75": "::game.S.title:: feels like a game we’ll remember as a distinctly ::game.S.releaseDate:: product: a glossy testament to the astonishing artistry and craft of games at this moment, and a reminder of how much room the medium still has to grow.",
  "general-76": "It is a special game because it rewards curiosity. The game encourages you to take a minute and look at your surroundings. To explore—poke and prod a little.",
  "general-77": "::game.S.title:: is not so much a game as it is an experience.",
}
