export default {
  "genre-0": "::game.S.title:: is one of the tightest, tensest ::game.S.genre:: games available.",
  "genre-1": "::game.S.title|possessive:: unique approach to ::game.S.genre:: spawned a genre now a staple of the game industry.",
  "genre-2": "It is one of the best ::game.S.genre:: games of all time.",
  "genre-3": "Its gameplay helped pave the way for other games to experiment with the genre, leading to a renaissance of ::game.S.genre:: games.",
  "genre-4": "It doesn't hurt that, upon release, players considered it one of the finest ::game.S.genre:: games ever made.",
  "genre-5": "It helped popularize the ::game.S.genre:: genre in America, which now has a strong cult following.",
  "genre-6": "One of the all time best ::game.S.genre:: games, it is simple dumb fun.",
  "genre-7": "Unparalleled in its depth and complexity, ::game.S.title:: raised the mark for all other ::game.S.genre:: games.",
  "genre-8": "::game.S.title:: revolutionized the ::game.S.genre:: genre with how many real world variables it threw at players.",
  "genre-9": "::game.S.title|possessive:: accessibility, gameplay, and systems made it easier to enjoy than most other ::game.S.genre:: games that had shipped before.",
  "genre-10": "::game.S.title:: challenged everything you'd commonly expect from ::game.s.genre|articlize:: experience.",
  "genre-11": "::game.S.title:: felt like ::game.s.genre|articlize:: game on steroids.",
  "genre-12": "::game.S.title:: is a more cartoony ::game.S.genre:: than others of its kind, something it leans into with its world and puzzle design.",
  "genre-13": "Though not the first of its type, ::game.S.title:: revolutionized the ::game.S.genre:: genre with how many real world variables it threw at players.",
  "genre-14": "::game.S.title:: is one of the best classic ::game.S.genre:: games.",
  "genre-15": "::game.S.title|possessive:: simple approach made it one of the best games in its genre.",
  "genre-16": "Combined with one of the more memorable stories told in games, ::game.S.title:: is often considered the best :game.S.genre:: game.",
  "genre-17": "Adding numerous new moves and mechanics that changed gameplay significantly, ::game.S.title:: was a successful attempt to update a once-stale ::game.S.genre::.",
  "genre-18": "Developed by only one person, ::game.S.title:: was one of ::game.S.releaseDate|possessive:: most talked-about games for its lighthearted approach to ::game.S.genre::.",
  "genre-19": "Its success not only changed how ::game.S.genre:: games were played, but also how the world looked at skateboarding.",
  "genre-20": "::game.S.title::, in a lot of ways, was more of the same for the ::game.S.genre:: genre.",
  "genre-21": "Every time you enjoy a ::game.S.genre::, remember to thank ::game.S.title::.",
  "genre-22": "::game.S.title:: was the template from which nearly every ::game.S.genre:: game drew inspiration.",
  "genre-23": "::game.S.title:: is among the pantheon of great ::game.S.genre:: games that turned video games from toys into a full blown business.",
  "genre-24": "The game had many features that became commonplace in ::game.S.genre:: after its release.",
  "genre-25": "::game.S.title:: caught the eyes of ::game.S.genre:: fans when it put a focus not only on speed, but on obliterating opponents.",
  "genre-26": "The game's success is, in part, credited with popularizing ::game.S.genre:: games around the globe.",
  "genre-27": "::game.S.title:: improved just about everything that had been in ::game.S.genre|articlize:: game up to that point, from the controls to the enemy AI to the gadgets.",
  "genre-28": "::game.S.title:: managed to walk a tightrope between being simple yet experimental, and many critics consider it the best ::game.S.genre:: game of all time.",
  "genre-29": "For ::game.S.title:: fans, it still stands out as one of the best representations of the genre in games.",
  "genre-30": "::game.S.title:: dominated the ::game.S.genre:: genre.",
  "genre-31": "::game.S.title:: distanced itself from other ::game.S.genre:: games with its extreme attention to detail.",
  "genre-32": "While ::game.S.genre:: games have a few forebears to their credit, none saw the same ubiquity and success as ::game.S.title::.",
  "genre-33": "::game.S.title:: is a master class in ::game.S.genre:: games, with a hero designed to appeal to, and inspire, a wide variety of gamers.",
  "genre-34": "Colorful, goofy and, most of all, fun, it was a far cry from the overly serious style of most ::game.S.genre:: games.",
  "genre-35": "::game.S.title:: is still loved not for reinventing the ::game.S.genre:: genre, but for nearly perfecting it.",
  "genre-36": "::game.S.title:: was massively innovative, changing the way ::game.s.genre:: games were played and how games in general approached navigation.",
  "genre-37": "::game.S.title:: played with the idea that ::game.S.genre:: games didn't have to harshly punish mistakes.",
  "genre-38": "::game.S.title|possessive:: thinking-man's approach to the ::game.S.genre:: genre became a blueprint for the genre going forward.",
  "genre-39": "::game.S.title:: is one of the best ::game.S.genre:: games of all time, and a hell of a time if played with another person.",
  "genre-40": "::game.S.title:: was the apex of the ::genre.S.genre:: genre.",
  "genre-41": "Best played with four players, it constantly bounced between genres but never suffered an identity crisis because of it.",
  "genre-42": "::game.S.title|possessive:: lighthearted approach helped pave the way for an influx of ::game.S.title:: games.",
  "genre-43": "Unprecedented in its size, the game set forth conventions and designs that'd define the ::game.S.genre:: genre going forward.",
  "genre-44": "It wasn't even close to being the first ::game.S.genre:: game, but ::game.S.title:: defined the genre after its ::game.S.releaseDate:: release.",
  "genre-45": "::game.S.title:: single-handedly made the ::game.S.genre:: genre what it is today.",
  "genre-46": "::game.S.title:: was never afraid to jerk the wheel, shifting genres and subverting gameplay tropes.",
  "genre-47": "::game.S.title:: more or less created the modern ::game.S.genre:: genre.",
  "genre-48": "The game sold better than nearly any other ::game.S.genre:: game at the time.",
  "genre-49": "Ultimately, it was so popular that it's sometimes credited for killing the traditional ::game.S.title:: game.",
  "genre-50": "Striving for a level of realism still pretty rare in games, the game combined classic adventure mechanics with an approach that would later be known as the ::game.genre:: genre.",
  "genre-51": "What seems like another boilerplate entry in the ::game.S.genre:: genre quickly establishes its own identity.",
  "genre-52": "Cloned and ported all over the place since, ::game.S.title:: is still one of the best ::game.S.genre:: games out there.",
  "genre-53": "A follow up to one of the most important ::game.S.genre:: games of all time, ::game.S.title:: expanded the gameplay with new challenges and collectibles.",
  "genre-54": "::game.S.title:: introduced a lot of mechanics that became staples in its genre.",
  "genre-55": "Almost like two games in one, ::game.S.title:: requires players to be thoughtful and skilled at its genre-bending format.",
  "genre-56": "::game.S.title:: set a lot of the standards people now expect from open world role-playing games.",
  "genre-57": "::game.S.title|possessive:: incredible depth and attention to detail redefined a genre all about living in a different world in a different life.",
  "genre-58": "::game.S.title:: still stands out as one of the higher-rated games in its genre.",
  "genre-59": "::game.S.title:: reinvented the ::game.S.genre:: genre by removing its primary mechanic.",
  "genre-60": "The release of this game established its developer as a world-leader in the ::game.S.genre:: genre.",
  "genre-61": "When it released, ::game.S.title:: was the freshest take in years of the popular ::game.S.genre:: genre.",
  "genre-62": "::game.S.title:: is a ::game.S.genre:: game for people who don’t yet know they like the genre.",
  "genre-63": "::game.S.title:: is a ::game.S.genre:: game without its traditional trappings. In your first hours playing, you aren’t just learning a new game; you’re actively working to forget the training of an entire genre.",
  "genre-64": "::game.S.title:: is a methodical reimagining of the ::game.S.genre:: franchise.",
  "genre-65": "It is a feverishly optimistic (and welcomingly naive) ::game.S.genre:: game inspired, in part, by the works of Studio Ghibli.",
  "genre-66": "::game.S.title:: is the rare tactics game that makes attrition a tool, not a mistake.",
}
