export default {
  "genre-0": "::game.S.title:: is one of the tightest, tensest ::game.S.genre:: games available.",
  "genre-1": "::game.S.title|possessive:: unique approach to ::game.S.genre:: spawned a genre now a staple of the game industry.",
  "genre-2": "It is one of the best ::game.S.genre:: games of all time.",
  "genre-3": "Its gameplay helped pave the way for other games to experiment with the genre, leading to a renaissance of ::game.S.genre:: games.",
  "genre-4": "It doesn't hurt that, upon release, players considered it one of the finest ::game.S.genre:: games ever made.",
  "genre-5": "It helped popularize the ::game.S.genre:: genre in America, which now has a strong cult following.",
  "genre-6": "One of the all time best ::game.S.genre:: games, TimeSplitters is simple dumb fun.",
  "genre-7": "Unparalleled in its depth and complexity, ::game.S.title:: raised the mark for all other ::game.S.genre:: games.",
  "genre-8": "::game.S.title:: revolutionized the ::game.S.genre:: genre with how many real world variables it threw at players.",
  "genre-9": "::game.S.title|possessive:: accessibility, gameplay, and systems made it easier to enjoy than most other ::game.S.genre:: games that had shipped before.",
  "genre-10": "::game.S.title:: challanged everything you'd commonly expect from ::game.s.genre|articlize:: experience.",
  "genre-11": "::game.S.title:: felt like ::game.s.genre|articlize:: game on steroids.",
  "genre-12": "::game.S.title:: is a more cartoony ::game.S.genre:: than others of its kind, something it leans into with its world and puzzle design.",
}
