export default {
  "plot-0": "::game.S.title:: told a wholesome story about friendship and how, even from different planets, we can find common ground.",
  "plot-1": "Equal parts John Huston and John Woo, it tells a story of love, addiction and tragedy, all tied together into a game.",
  "plot-2": "Greater than the sum of its parts, the story ::game.S.title:: tells about post-apocalyptic capitalism makes it an important example of games as political satire.",
  "plot-3": "Telling a semi-mature story about the dangers of robot sentience, ::game.S.title:: reinvented the :game.S.genre:: genre.",
  "plot-4": "::game.S.title:: told a story about becoming a professional skater.",
  "plot-5": "Bathed in the dying light of a crumbling rural town, ::game.S.title:: follows an aging truck driver as he delivers his final package to an address that can only be reached by a highway buried deep in the caves of Kentucky.",
  "plot-6": "This game is a journey through an America whose sun is setting, a place of tragic beauty where economic decline is painted in dream-like brush strokes of magical realism.",
  "plot-7": "The game allows players to explore its dystopian United States in great detail.",
  "plot-8": "The developers showed that they could make one of the best endings the game industry has ever seen.",
  "plot-9": "On the surface a game about space politics and intergalactic war, ::game.S.title:: is more memorable for the deep, emotional relationships with which the player could engage.",
  "plot-10": "::game.S.title:: pointed an angry finger right at the American dream.",
  "plot-11": "::game.S.title:: was a bleak, violent look at what life could be like for an immigrant.",
  "plot-12": "At the time of its release, ::game.S.title:: was unparalleled in its intense portrayal of war",
  "plot-13": "::game.S.title:: stood out as a game unafraid to examine sexuality in smart, nuanced ways — something hard to say about most games",
  "plot-14": "::game.S.title|possessive:: mature take on infidelity, lust, love and abuse showed the depth that game stories could achieve.",
  "plot-15": "::game.S.title:: is all about the tranquility of a simple life.",
  "plot-16": "Allowing players to decide how to tackle daily activities, ::game.S.title:: turned the mundanities of life into soothing, charming experiences.",
  "plot-17": "Telling a surprisingly emotional story about gang life and the difficulties of escaping it, ::game.S.title:: was a watershed moment.",
  "plot-18": "::game.S.title:: is said to be a view of America from those who don’t live there, but that excludes the painstaking nostalgic touches infused throughout.",
  "plot-19": "Its greatest mission is \"Home Coming.\" The main character, after having gone through hell — returns to a family that had seen better days as well.",
  "plot-20": "In ::game.S.title::, you're out to help those in need — through the power of dance.",
  "plot-21": "::game.S.title:: was a bleak story about science gone wrong.",
  "plot-22": "Essentially putting you on a suicide mission, the game built upon its deep relationships by placing your favorite characters' lives in your hands.",
  "plot-23": "The game tasked players with creating and upgrading their weapons as they journeyed alone through catacombs.",
  "plot-24": "The game's deep story and trope-breaking found success around the world.",
  "plot-25": "::game.S.title:: is full of inventive, weird puzzles and a genuinely funny script about the misadventures of pirates.",
  "plot-26": "::game.S.title:: is about staying alive — even when it seems impossible.",
  "plot-27": "It tells a brutal, yet intimate post-apocalyptic story with some of the finest examples of character development in games.",
  "plot-28": "::game.S.title|possessive:: tale of love, lies and the human condition set a new bar for storytelling in games — one that'll be hard to top.",
  "plot-29": "Terrifying, tense and open-ended, ::game.S.title:: earns special praise for its story of AI sentience.",
  "plot-30": "A cult classic, ::game.S.title|possessive:: rich story gets points for being smarter than its peers, casting players as a selfish protagonist with surprising depth.",
  "plot-31": "The game tasked players with running a successful dynasty and appointing an heir.",
  "plot-32": "Telling the story of two brothers, each controlled differently, the game's unique set-up tested the bonds of family.",
  "plot-33": "Lauded for its emotional story, ::game.S.title:: was about learning to work together, all the while growing closer.",
  "plot-34": "The masterfulness in which ::game.S.title:: told its story of world travel, and the nuances and complexities in which the story is dissected by player choice, is one of the finer examples storytelling in video games.",
  "plot-35": "::game.S.title:: was an emotional tale of revenge.",
  "plot-36": "::game.S.title:: changed everything we knew about game writing. Focusing on the impact of every decision, it presented numerous heart-stopping experiences.",
  "plot-37": "::game.S.title:: asked a near-impossible-to-answer question: How far will you go to save someone's life?",
  "plot-38": "The game's '60s chic, hilarious script and gadgets would make a Bond blush.",
  "plot-39": "It taught its players about American history while being immensely fun and engaging to interact with over the course of the game's long journey.",
  "plot-40": "Centered around investigating computer files in an effort to find information, ::game.S.title:: tells its story by dragging players down a rabbit hole of mystery in the pursuit of truth.",
  "plot-41": "The push and pull of the job and the personal life of your character made ::game.S.title:: an emotional experience, one emphasizing empathy over economic growth.",
  "plot-42": "Few games match the pacing of ::game.S.title::.",
  "plot-43": "Seemingly down to the second, ::game.S.title:: knew exactly when to put players through amazing set pieces, when to introduce puzzles and when to pull back for quieter, more intimate moments.",
  "plot-44": "::game.S.title:: was an amazing breakthrough in storytelling and a surprising reinvention of one of the oldest genres.",
  "plot-45": "::game.S.title:: told the personal stories of wartime soldiers with unmatched bombast never seen before in games.",
  "plot-46": "::game.S.title:: ushered in a new era of intense plot, narration and dialog everywhere, but particularly in the ::game.S.genre:: genre.",
  "plot-47": "The macabre underwater fantasy that was ::game.S.title:: left an impression on gamers that has rarely been matched.",
  "plot-48": "Telling a complex story about the nature of man, ::game.S.title:: offered one of the most unforgettable experiences in games.",
  "plot-49": "Somber and contemplative, ::game.S.title:: explores the life of rural America, both in its simplicity and its bizarreness.",
  "plot-50": "The game puts the lives of others in your hands — possibly at the cost of your family's safety. Upon its release, ::game.S.title:: was lauded for its intense moral dilemmas.",
  "plot-51": "::game.S.title:: was masterclass in how to write a plot twist and how to smash player expectations.",
  "plot-52": "::game.S.title:: leaves it up to the player to imagine the events of a heist gone wrong, telling a short, out-of-order story.",
  "plot-53": "Inspired by real-world events like the Gulf War, ::game.S.title:: was partly responsible for the popularization of modern war settings in games.",
  "plot-54": "::game.S.title:: let players become who they wanted.",
}
