export default {
  "plot-0": "::game.S.title:: told a wholesome story about friendship and how, even from different planets, we can find common ground.",
  "plot-1": "Equal parts John Huston and John Woo, it tells a story of love, addiction and tragedy, all tied together into a game.",
  "plot-2": "Greater than the sum of its parts, the story ::game.S.title:: tells about post-apocalyptic capitalism makes it an important example of games as political satire.",
  "plot-3": "Telling a semi-mature story about the dangers of robot sentience, ::game.S.title:: reinvented the :game.S.genre:: genre.",
  "plot-4": "::game.S.title:: told a story about becoming a professional skater.",
  "plot-5": "Bathed in the dying light of a crumbling rural town, ::game.S.title:: follows an aging truck driver as he delivers his final package to an address that can only be reached by a highway buried deep in the caves of Kentucky.",
  "plot-6": "This game is a journey through an America whose sun is setting, a place of tragic beauty where economic decline is painted in dream-like brush strokes of magical realism.",
  "plot-7": "The game allows players to explore its dystopian United States in great detail.",
  "plot-8": "The developers showed that they could make one of the best endings the game industry has ever seen.",
  "plot-9": "On the surface a game about space politics and intergalactic war, ::game.S.title:: is more memorable for the deep, emotional relationships with which the player could engage.",
  "plot-10": "::game.S.title:: pointed an angry finger right at the American dream.",
  "plot-11": "::game.S.title:: was a bleak, violent look at what life could be like for an immigrant.",
  "plot-12": "At the time of its release, ::game.S.title:: was unparalleled in its intense portrayal of war",
  "plot-13": "::game.S.title:: stood out as a game unafraid to examine sexuality in smart, nuanced ways — something hard to say about most games",
  "plot-14": "::game.S.title|possessive:: mature take on infidelity, lust, love and abuse showed the depth that game stories could achieve.",
  "plot-15": "::game.S.title:: is all about the tranquility of a simple life.",
  "plot-16": "Allowing players to decide how to tackle daily activities, ::game.S.title:: turned the mundanities of life into soothing, charming experiences.",
  "plot-17": "Telling a surprisingly emotional story about gang life and the difficulties of escaping it, ::game.S.title:: was a watershed moment.",
  "plot-18": "::game.S.title:: is said to be a view of America from those who don’t live there, but that excludes the painstaking nostalgic touches infused throughout.",
  "plot-19": "Its greatest mission is \"Home Coming.\" The main character, after having gone through hell — returns to a family that had seen better days as well.",
  "plot-20": "In ::game.S.title::, you're out to help those in need — through the power of dance.",
  "plot-21": "::game.S.title:: was a bleak story about science gone wrong.",
  "plot-22": "Essentially putting you on a suicide mission, the game built upon its deep relationships by placing your favorite characters' lives in your hands.",
}
