export default {
  "plot-0": "Telling a semi-mature story about the dangers of robot sentience, ::game.S.title:: reinvented the :game.S.genre:: genre.",
  "plot-1": "::game.S.title:: tells a story about becoming a ::game.vocation::.",
  "plot-2": "Bathed in the dying light of ::game.location::, ::game.S.title:: follows ::game.personality|articlize:: ::game.vocation:: to a place that can only be reached by a highway buried deep in the caves.",
  "plot-3": "This game is a journey through ::game.location|articlize:: whose sun is setting, a place of tragic beauty painted in dream-like brush strokes of magical realism.",
  "plot-4": "The developers showed that they could make one of the best endings the game industry has ever seen.",
  "plot-5": "The game allows players to explore its ::game.setting:: ::game.location:: in great detail.",
  "plot-6": "::game.S.title:: was a bleak, violent look at what life could be like for an immigrant.",
  "plot-7": "At the time of its release, ::game.S.title:: was unparalleled in its ::game.adjective:: portrayal of ::game.concept::.",
  "plot-8": "::game.S.title:: is all about the tranquility of a simple life.",
  "plot-9": "Allowing players to decide how to tackle daily activities, ::game.S.title:: turned the mundanities of life into soothing, charming experiences.",
  "plot-10": "Telling a surprisingly emotional story about gang life and the difficulties of escaping it, ::game.S.title:: was a watershed moment.",
  "plot-11": "::game.S.title:: is said to be a view of ::game.location:: from those who don’t live there, but that excludes the painstaking nostalgic touches infused throughout.",
  "plot-12": "In its greatest mission, \"Home Coming.\", the main character, returns to a family that has gone through hell.",
  "plot-13": "In ::game.S.title::, you're out to help those in need — through the power of dance.",
  "plot-14": "Essentially putting you on a suicide mission, the game built upon its deep relationships by placing your favorite characters' lives in your hands.",
  "plot-15": "The game tasked players with creating and upgrading their weapons as they journeyed alone through ::game.setting|articlize:: ::game.location::.",
  "plot-16": "::game.S.title:: is full of inventive, weird puzzles and a genuinely ::game.adjective:: script about the misadventures of ::game.vocation|pluralize::.",
  "plot-17": "Terrifying, tense, and open-ended, ::game.S.title:: earns special praise for its story of AI sentience.",
  "plot-18": "The game tasked players with running a successful dynasty in and appointing an heir.",
  "plot-19": "Telling the story of two brothers, each controlled differently, the game's unique set-up tested the bonds of family.",
  "plot-20": "::game.S.title:: was an emotional tale of revenge.",
  "plot-21": "::game.S.title:: asked a near-impossible-to-answer question: How far will you go to save someone's life?",
  "plot-22": "The game's '60s chic, hilarious script and gadgets would make a Bond blush.",
  "plot-23": "Centered around investigating computer files in an effort to find information, ::game.S.title:: tells its story by dragging players down a rabbit hole of mystery in the pursuit of truth.",
  "plot-24": "::game.S.title:: told the personal stories of wartime soldiers with unmatched bombast never seen before in games.",
  "plot-25": "::game.adjective|capitalize:: and contemplative, ::game.S.title:: explores the life of ::game.setting|articlize:: ::game.Place::, both in its simplicity and its bizarreness.",
  "plot-26": "::game.S.title:: leaves it up to the player to imagine the events of a heist gone wrong, telling a short, out-of-order story.",
  "plot-27": "Inspired by real-world events like the Gulf War, ::game.S.title:: was partly responsible for the popularization of the modern war setting in games.",
  "plot-28": "Constantly changing, constantly rotating, ::game.S.title:: was a mind-bending exploration of ::game.setting|articlize:: ::game.location:: and what many critics felt was a nonsensical story.",
  "plot-29": "Combined with a conspiracy plot revolving around ::game.S.setting|articlize:: ::game.S.location::, ::game.S.title:: let players choose how important fidelity is to them, giving them complete freedom to let their relationships go up in flames.",
  "plot-30": "Pitting players against a race of enormous aliens and offering them over 100 guns to take the beasts down, the world is a playground.",
  "plot-31": "The game featured no heads-up display as players were tasked with breaking out of ::game.S.setting|articlize:: ::game.S.location:: by seemingly any means necessary.",
  "plot-32": "The objective of ::game.S.title:: is pretty simple: fight the bad guys.",
  "plot-33": "Taking place primarily in ::game.setting|articlize:: ::game.location|possessive:: streets, ::game.S.title:: is as much about survival horror as it is survival in the wake of tragedy.",
  "plot-34": "It presents a coherent vision of ::game.setting|articlize:: ::game.location:: filled with enough sex, guns, and rock-and-roll to make even a hardcore ’80s rockstar blush.",
  "plot-35": "The game told an emotional ::game.S.genre:: story about gig labor, tech disruption & the experience of being a ::game.vocaton::.",
  "plot-36": "Its story is akin to a fully realized drama that plays out like a TV-miniseries, exploring themes like family, parenthood, aging and family legacies.",
  "plot-37": "It tells the story of two teenage girls trapped in ::game.setting|articlize:: ::game.location::.",
  "plot-38": "It features a memorable story about a brutal war, a conflict in which your ::game.personality:: ::game.vocation:: faces off against an evil regime that stands in your way.",
  "plot-39": "::game.S.title:: would feel like a Pixar movie, were it not so fascinated with the death of human civilization at the hands (claws? maws?) of grotesque aliens.",
  "plot-40": "It’s a game you feel in your gut, where you help topple a totalitarian regime by leaving a trail of broken and twisted mechs, as well as their dead pilots, littered across the stars.",
  "plot-41": "The game is built around medieval and Renaissance politics played-out across the galaxy, with massive piloted mechs taking the place of the mounted knight.",
  "plot-42": "A dense, anxiety-inducing exploration of rot—the kind that tears apart bodies and the kind that tears apart towns—this is the perfect game for a rainy, moody day.",
  "plot-43": "It is an open-world ::game.vocation:: tale, setting players on a mission in ::game.setting|articlize:: ::game.location:: to track down and take vengeance upon the desperado what done murdered your family.",
  "plot-44": "::game.S.title:: takes place entirely in the menacing, ::game.setting|articlize:: ::game.location::, full of antagonistic spirits and uncanny assemblages of real-world objects.",
  "plot-45": "::game.S.title:: is a game that dares to ask the question, \"What if you played dodgeball with bats and balls and also it was anime as hell?\"",
  "plot-46": "A little bit Poe and a whole lot Lovecraft, it has you fumbling around dark Victorian manors and stumbling into an ancient and probably very evil mystery.",
  "plot-47": "::game.S.title:: is about ::game.vocation|articlize:: who ignores a whole bunch of foreboding signs and decides to embark on a journey that he believes will allow him to look into the future.",
  "plot-48": "::game.S.title|possessive:: appeal lies in randomized 10-minute stories about people coping with impending doom, ones that are meant to be generated again and again and shared with a few equally doomed friends.",
  "plot-49": "::game.S.title:: sends players soaring through alien landscapes and down thrilling valley dives with nothing but their wings.",
  "plot-50": "::game.S.title:: let the player experience the minutiae of being ::game.vocation|articlize::.",
  "plot-51": "::game.S.title:: details the struggles of ::game.vocation|articlize:: coping with ::game.concept|capitalize::.",
  "plot-52": "Nothing came to close to ::game.S.title|possessive:: ::game.adjective:: portrayal of ::game.concept:: when it released in ::game.S.releaseDate::.",
  "plot-53": "By getting to choose how tackle daily activities, the player got to turn the banalities of ::game.vocation:: life into soothing, charming experiences.",
  "plot-54": "::game.S.title:: told the story of a young immigrant to ::game.setting|articlize:: ::game.location:: that had to begin life anew while picking up the trade of ::game.vocation|articlize::.",
  "plot-55": "::game.S.title:: is a universal story about ::game.concept:: tastefully spiced with complicated emotions.",
  "plot-56": "Its story captured the feeling of being a 20-something ::game.S.vocation:: and feeling stuck on a path carrying you to a predetermined destination.",
}
