export default {
  "review-0": "While many reviews were semi-positive and the game has built a cult following since its release, the developer closed shortly after its release, making ::game.S.title:: its final game.",
  "review-1": "The game is a \"relaxing adventure\" that never takes advantage of its players, according to ::site.title::.",
  "review-2": "As ::site.title|possessive:: review put it, it \"is as beautiful as it is engaging.\"",
  "review-3": "Upon the game's release, many loved the abilities that allowed for worlds to be traversed in different ways other than just running and jumping, but were put off by the lack of polish and issues with the camera.",
  "review-4": "\"It is unflinchingly ambitious in a way that few games are,\" according to ::site.title::.",
  "review-5": "When it released, ::site.title:: said the game \"grabbed the gaming world with its color and imaginative design.\"",
  "review-6": "The changing weather, time of day, and new coordinate systems were seen as so realistic, the game's advertising claimed if it were any more lifelike \"you'd need a license.\"",
  "review-7": "Considered one of ::site.title|possessive:: 10 most important games, ::game.S.title:: was one of the more complex games of ::game.S.releaseDate::.",
  "review-8": "::game.S.title:: is one of the highest-rated ::game.S.genre:: games of all time.",
  "review-9": "::game.S.title:: was a precisely balanced game, \"perhaps one of the most finely tuned... of all time,\" according to ::site.title::.",
  "review-10": "When it released, the game was praised for its evolution of ::game.S.genre::-style gameplay",
  "review-11": "::game.S.title:: was a \"metagame-within-a-game… [where] anything could and probably would happen,\" according to ::site.title::.",
  "review-12": "Players all around the world fell in love with the game because of its catchy soundtracks and its unique mix of showmanship and technical performance.",
  "review-13": "Thanks to a combination of old and new elements, ::game.S.title:: resonated immensely with fans and critics.",
  "review-14": "Today, it still retains the ::game.S.genre:: genre's highest Metacritic score.",
  "review-15": "::site.title:: called it \"quite possibly the perfect ::game.S.genre:: game.\"",
  "review-16": "It was called \"the best space combat game ever made\" by ::site.title:: upon its release.",
  "review-17": "Reviews have since praised the game for its striking visuals, great gameplay and wonderful soundtrack.",
  "review-18": "::game.S.title:: is ageless and perfect.",
  "review-19": "Most critics were surprised that such a low budget game shipped with the quality it did.",
  "review-20": "As ::site.title|possessive:: review put it, \"Even at its most unrecognizable, it's one of the most joyous multiplayer experiences we've ever been a part of.\"",
  "review-21": "::game.S.title:: \"obliterated\" the bar for online gaming when it released in ::game.S.releaseDate::, according to ::site.title::.",
  "review-22": "::game.S.title|possessive:: dark world and addictive loot-based gameplay received critical and fan praise.",
  "review-23": "::game.S.title:: received numerous perfect scores and spots on greatest games of all time lists.",
  "review-24": "The game reviewed to universal acclaim, with many praising its challenging gameplay.",
  "review-25": "::site.title:: noted that the game was \"a sufficiently convincing universe of otherness that consumed your time while playing, and your attention when not.\"",
  "review-26": "It is, as ::site.title:: said, \"perhaps the most ingenious and inspired idea ever for a game.\"",
  "review-27": "::game.S.title:: is, as one writer puts it, \"arguably the most important ::game.S.genre:: game ever made.\"",
  "review-28": "When this ::game.S.genre:: game released in ::game.S.releaseDate::, it was met with immense backlash and criticism, but the developer's intense commitment to the project led to a game that accrued millions of devoted players.",
  "review-29": "::site.title::, in it's review, named it \"some kind of ludicrous masterpiece\".",
  "review-30": "Here’s ::site.title:: laying out everything you need to know about ::game.S.title::, \“To answer the most pressing questions about it: Yes, this game lets you be best friends with a cat.\”",
  "review-31": "Here’s the take from ::site.title|possessive::, \“There’s not a wasted breath or a plot point that doesn’t manage to pay off in a significant way. ::game.S.title:: is a solid contemporary ::game.S.genre:: game that brings a lot of design ideas into sharp, clear focus while staying entertaining and engaging throughout.\”",
};
