export default {
  "review-0": "While many reviews were semi-positive and the game has built a cult following since its release, the developer closed shortly after its release, making ::game.S.title:: its final game.",
  "review-1": "The game is a \"relaxing adventure\" that never takes advantage of its players, according to ::site.title::.",
  "review-2": "As ::site.title|possessive:: review put it, it \"is as beautiful as it is engaging.\"",
  "review-3": "Upon the game's release, many loved the abilities that allowed for worlds to be traversed in different ways other than just running and jumping, but were put off by the lack of polish and issues with the camera.",
  "review-4": "\"It is unflinchingly ambitious in a way that few games are,\" according to ::site.title::.",
  "review-5": "When it released, ::site.title:: said the game \"grabbed the gaming world with its color and imaginative design.\"",
  "review-6": "The changing weather, time of day, and new coordinate systems were seen as so realistic, the game's advertising claimed if it were any more lifelike \"you'd need a license.\"",
  "review-7": "Considered one of ::site.title|possessive:: 10 most important games, ::game.S.title:: was one of the more complex games of ::game.S.releaseDate::.",
  "review-8": "::game.S.title:: is one of the highest-rated ::game.S.genre:: games of all time.",
  "review-9": "::game.S.title:: was a precisely balanced game, \"perhaps one of the most finely tuned... of all time,\" according to ::site.title::.",
  "review-10": "When it released, the game was praised for its evolution of ::game.S.genre::-style gameplay",
  "review-11": "::game.S.title:: was a \"metagame-within-a-game… [where] anything could and probably would happen,\" according to ::site.title::.",
  "review-12": "Players all around the world fell in love with the game because of its catchy soundtracks and its unique mix of showmanship and technical performance.",
  "review-13": "Thanks to a combination of old and new elements, ::game.S.title:: resonated immensely with fans and critics.",
  "review-14": "Today, it still retains the ::game.S.genre:: genre's highest Metacritic score.",
  "review-15": "::site.title:: called it \"quite possibly the perfect ::game.S.genre:: game.\"",
  "review-16": "It was called \"the best space combat game ever made\" by ::site.title:: upon its release.",
  "review-17": "Reviews have since praised the game for its striking visuals, great gameplay and wonderful soundtrack.",
  "review-18": "::game.S.title:: is ageless and perfect.",
  "review-19": "Most critics were surprised that such a low budget game shipped with the quality it did.",
  "review-20": "As ::site.title|possessive:: review put it, \"Even at its most unrecognizable, it's one of the most joyous multiplayer experiences we've ever been a part of.\"",
  "review-21": "::game.S.title:: \"obliterated\" the bar for online gaming when it released in ::game.S.releaseDate::, according to ::site.title::.",
  "review-22": "::game.S.title|possessive:: dark world and addictive loot-based gameplay received critical and fan praise.",
  "review-23": "::game.S.title:: received numerous perfect scores and spots on greatest games of all time lists.",
  "review-24": "The game reviewed to universal acclaim, with many praising its challenging gameplay.",
};
